//user
export const USER_START_LOGIN         = 'USER_START_LOGIN'
export const USER_SUCCESSFULLY_LOGGED = 'USER_SUCCESSFULLY_LOGGED'
export const USER_LOGIN_FAILED        = 'USER_LOGIN_FAILED'
export const USER_START_REGISTER      = 'USER_START_REGISTER'
export const USER_REGISTER_FAILED     = 'USER_REGISTER_FAILED'
export const USER_LOGGED_OUT          = 'USER_LOGGED_OUT'
